--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Diduhless/Parties
build-by-default: true
projects:
  Parties:
    path: ""
    icon: "icon.png"
    libs:
      - src: dresnite/easyui/libEasyUI
        version: 1.0.3
        branch: pm5
...
